apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T02:43:15Z"
  name: carts-canary
  resourceVersion: "1146335"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 2557a341-1c89-11ea-92a4-42010a980021
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
